api_health_check:
    route: /api/health
    module: api
    action: health
    parameters:
        format: json
    csrf_enabled: false

api_authentication:
    route: /api/auth
    module: api
    action: auth
    parameters:
        format: json
    csrf_enabled: false

api_user_details:
    route: /api/me
    module: api
    action: me
    parameters:
        format: json
    csrf_enabled: false
    
api_user_teams:
    route: /api/teams
    module: api
    action: listTeams
    parameters:
        format: json
    csrf_enabled: false
    
api_activity_types:
    route: /api/activitytypes
    module: api
    action: listActivityTypes
    parameters:
        format: json
    csrf_enabled: false

api_list_user_projects:
    route: /api/userprojects
    module: api
    action: listUserProjects
    parameters:
        format: json
    csrf_enabled: false

api_list_projects:
    route: /api/projects
    module: api
    action: listProjects
    parameters:
        format: json
    csrf_enabled: false

api_issue_by_project:
    route: /api/projects/:project_id/issues
    module: api
    action: listIssuesByProject
    parameters:
        format: json
    csrf_enabled: false
    
  
api_list_editions:
    route: /api/projects/:project_id/editions
    module: api
    action: listEditions
    parameters:
        format: json
    csrf_enabled: false

api_project_components:
    route: /api/projects/:project_id/components
    module: api
    action: listComponents
    parameters:
        format: json
    csrf_enabled: false

api_list_issues_type_by_project:
    route: /api/projects/:project_id/issuetypes
    module: api
    action: listIssueTypes
    parameters:
        format: json
    csrf_enabled: false

api_list_fields_by_issuetypes:
    route: /api/projects/:project_id/issuetypes/:issue_type/fields
    module: api
    action: listFieldsByIssueType
    parameters:
        format: json
    csrf_enabled: false
    

api_list_activities_by_projects:
    route: /api/projects/activities
    module: api
    action: listActivitiesByProjects
    parameters:
        format: json
    csrf_enabled: false

api_issues:
    route: /api/issues
    module: api
    action: issues
    parameters:
        format: json
    csrf_enabled: false
    
api_list_user_related_issues:
    route: /api/issues/related
    module: api
    action: listUserRelatedIssues
    parameters:
        format: json
    csrf_enabled: false

api_list_user_time_spent:
    route: /api/issues/timespent
    module: api
    action: listTimeSpentBetweenDates
    parameters:
        format: json
    csrf_enabled: false

api_issues_by_recent_activities:
    route: /api/issues/recent
    module: api
    action: listIssuesByRecentActivities
    parameters:
        format: json
    csrf_enabled: false
    
api_list_assigned_issues:
    route: /api/issues/assigned
    module: api
    action: listAssignedIssues
    parameters:
        format: json
    csrf_enabled: false
    
api_list_starred_issues:
    route: /api/issues/starred
    module: api
    action: listStarredIssues
    parameters:
        format: json
    csrf_enabled: false

api_list_user_activities:
    route: /api/activities
    module: api
    action: listActivities
    parameters:
        format: json
    csrf_enabled: false

api_issue_by_id:
    route: /api/issues/:issue_id/getIssue
    module: api
    action: getIssueByID
    parameters:
        format: json
    csrf_enabled: false

api_list_activities_by_issue:
    route: /api/issues/:issue_id/activities
    module: api
    action: activities
    parameters:
        format: json
    csrf_enabled: false

api_toggle_favourite_issue:
    route: /api/issues/:issue_id/toggle-favourite
    module: api
    action: toggleFavouriteIssue
    parameters:
        format: json
    csrf_enabled: false

api_list_modify_activity:
    route: /api/activities/:activity_id/edit
    module: api
    action: modifyActivity
    parameters:
        format: json
    csrf_enabled: false
    
api_list_move_activity:
    route: /api/activities/:activity_id/move
    module: api
    action: moveActivity
    parameters:
        format: json
    csrf_enabled: false

api_list_delete_activity:
    route: /api/activities/:activity_id/delete
    module: api
    action: deleteActivity
    parameters:
        format: json
    csrf_enabled: false
