api_health_check:
    route: /api/health
    module: api
    action: health
    parameters: [ ]
    csrf_enabled: false

api_authentication:
    route: /api/auth
    module: api
    action: auth
    parameters: [ ]
    csrf_enabled: false

api_user_details:
    route: /api/me
    module: api
    action: me
    parameters: [ ]
    csrf_enabled: false

api_list_user_projects:
    route: /api/projects
    module: api
    action: listProjects
    parameters: [ ]
    csrf_enabled: false

api_list_user_issues:
    route: /api/issues
    module: api
    action: listIssues
    parameters: [ ]
    csrf_enabled: false
    
api_list_recent_issues:
    route: /api/issues/recent
    module: api
    action: listRecentIssues
    parameters: [ ]
    csrf_enabled: false
    
api_list_assigned_issues:
    route: /api/issues/assigned
    module: api
    action: listAssignedIssues
    parameters: [ ]
    csrf_enabled: false
    
api_list_issues_type_by_project:
    route: /api/issues/types
    module: api
    action: listIssueTypes
    parameters: [ ]
    csrf_enabled: false
    
api_list_starred_issues:
    route: /api/issues/starred
    module: api
    action: listStarredIssues
    parameters: [ ]
    csrf_enabled: false

api_toggle_favourite_issue:
    route: /api/issues/:issue_id/toggle_favourite
    module: api
    action: toggleFavouriteIssue
    parameters: [ ]
    csrf_enabled: false