api_health_check:
    route: /api/health
    module: api
    action: health
    parameters: [ ]
    csrf_enabled: false

api_authentication:
    route: /api/auth
    module: api
    action: auth
    parameters: [ ]
    csrf_enabled: false

api_user_details:
    route: /api/auth/me
    module: api
    action: me
    parameters: [ ]
    csrf_enabled: false

api_list_user_projects:
    route: /api/projects
    module: api
    action: listProjects
    parameters: [ ]
    csrf_enabled: false